[project]
name = "mcp-exp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.2.0",
    "loguru>=0.7.3",
    "mcp[cli]>=1.9.0",
]
